kind: ConfigMap
apiVersion: v1
metadata:
  name: domain-config
  namespace: datapower
  selfLink: /api/v1/namespaces/datapower/configmaps/domain-config
  uid: 8d61c08f-36c3-44a7-9ad3-67218aa4db48
  resourceVersion: '15133122'
  creationTimestamp: '2021-08-30T18:23:31Z'
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: v1
      time: '2021-08-30T18:23:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data': {}
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2021-08-31T09:50:38Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          'f:default.cfg': {}
data:
  default.cfg: >
    top; configure terminal; suppress-warnings; exec config:///auto-user.cfg; no suppress-warnings

    crypto
      certificate "webmgmt-cert" "sharedcert:///myCA.pem"
    exit

    crypto
      key "webmgmt-key" "sharedcert:///myCA.key"
    exit

    crypto
      idcred "webmgmt-credentials" "webmgmt-key" "webmgmt-cert"
    exit

    crypto
      
    %if% available "ssl-server"

    ssl-server "webmgmt-service"
      protocols "TLSv1d1+TLSv1d2+TLSv1d3" 
      ciphers AES_256_GCM_SHA384
      ciphers CHACHA20_POLY1305_SHA256
      ciphers AES_128_GCM_SHA256
      ciphers ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      ciphers ECDHE_RSA_WITH_AES_256_GCM_SHA384
      ciphers ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
      ciphers ECDHE_RSA_WITH_AES_256_CBC_SHA384
      ciphers ECDHE_ECDSA_WITH_AES_256_CBC_SHA
      ciphers ECDHE_RSA_WITH_AES_256_CBC_SHA
      ciphers DHE_DSS_WITH_AES_256_GCM_SHA384
      ciphers DHE_RSA_WITH_AES_256_GCM_SHA384
      ciphers DHE_RSA_WITH_AES_256_CBC_SHA256
      ciphers DHE_DSS_WITH_AES_256_CBC_SHA256
      ciphers DHE_RSA_WITH_AES_256_CBC_SHA
      ciphers DHE_DSS_WITH_AES_256_CBC_SHA
      ciphers RSA_WITH_AES_256_GCM_SHA384
      ciphers RSA_WITH_AES_256_CBC_SHA256
      ciphers RSA_WITH_AES_256_CBC_SHA
      ciphers ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      ciphers ECDHE_RSA_WITH_AES_128_GCM_SHA256
      ciphers ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
      ciphers ECDHE_RSA_WITH_AES_128_CBC_SHA256
      ciphers ECDHE_ECDSA_WITH_AES_128_CBC_SHA
      ciphers ECDHE_RSA_WITH_AES_128_CBC_SHA
      ciphers DHE_DSS_WITH_AES_128_GCM_SHA256
      ciphers DHE_RSA_WITH_AES_128_GCM_SHA256
      ciphers DHE_RSA_WITH_AES_128_CBC_SHA256
      ciphers DHE_DSS_WITH_AES_128_CBC_SHA256
      ciphers DHE_RSA_WITH_AES_128_CBC_SHA
      ciphers DHE_DSS_WITH_AES_128_CBC_SHA
      ciphers RSA_WITH_AES_128_GCM_SHA256
      ciphers RSA_WITH_AES_128_CBC_SHA256
      ciphers RSA_WITH_AES_128_CBC_SHA
      idcred webmgmt-credentials
      no request-client-auth 
      require-client-auth 
      validate-client-cert 
      send-client-auth-ca-list 
      caching 
      cache-timeout 300
      cache-size 20
      ssl-options "" 
      max-duration 60
      max-renegotiation-allowed 0
      no prohibit-resume-on-reneg 
      no compression 
      no allow-legacy-renegotiation 
      prefer-server-ciphers 
      curves secp521r1
      curves secp384r1
      curves secp256k1
      curves secp256r1
      no prioritize-chacha 
    exit

    %endif%

    exit


    web-mgmt
      admin-state "enabled"
      local-address "0.0.0.0" "9090"
      save-config-overwrite 
      idle-timeout 0
      ssl-config-type server
      ssl-server webmgmt-service
      no disable-csrf 
      enable-sts 
    exit
