kind: ConfigMap
apiVersion: v1
metadata:
  name: domain-config
  namespace: datapower
  uid: 9f270f69-e318-48ee-a8ba-61a3b0467178
  resourceVersion: '886950'
  creationTimestamp: '2022-04-06T15:23:41Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"default.cfg":"top; configure terminal;
      suppress-warnings; exec config:///auto-user.cfg; no
      suppress-warnings\ncrypto\n  certificate \"webmgmt-cert\"
      \"sharedcert:///myCA.pem\"\nexit\ncrypto\n  key \"webmgmt-key\"
      \"sharedcert:///myCA.key\"\nexit\ncrypto\n  idcred \"webmgmt-credentials\"
      \"webmgmt-key\" \"webmgmt-cert\"\nexit\ncrypto\n  \n%if% available
      \"ssl-server\"\nssl-server \"webmgmt-service\"\n  protocols
      \"TLSv1d1+TLSv1d2+TLSv1d3\" \n  ciphers AES_256_GCM_SHA384\n  ciphers
      CHACHA20_POLY1305_SHA256\n  ciphers AES_128_GCM_SHA256\n  ciphers
      ECDHE_ECDSA_WITH_AES_256_GCM_SHA384\n  ciphers
      ECDHE_RSA_WITH_AES_256_GCM_SHA384\n  ciphers
      ECDHE_ECDSA_WITH_AES_256_CBC_SHA384\n  ciphers
      ECDHE_RSA_WITH_AES_256_CBC_SHA384\n  ciphers
      ECDHE_ECDSA_WITH_AES_256_CBC_SHA\n  ciphers
      ECDHE_RSA_WITH_AES_256_CBC_SHA\n  ciphers
      DHE_DSS_WITH_AES_256_GCM_SHA384\n  ciphers
      DHE_RSA_WITH_AES_256_GCM_SHA384\n  ciphers
      DHE_RSA_WITH_AES_256_CBC_SHA256\n  ciphers
      DHE_DSS_WITH_AES_256_CBC_SHA256\n  ciphers DHE_RSA_WITH_AES_256_CBC_SHA\n 
      ciphers DHE_DSS_WITH_AES_256_CBC_SHA\n  ciphers
      RSA_WITH_AES_256_GCM_SHA384\n  ciphers RSA_WITH_AES_256_CBC_SHA256\n 
      ciphers RSA_WITH_AES_256_CBC_SHA\n  ciphers
      ECDHE_ECDSA_WITH_AES_128_GCM_SHA256\n  ciphers
      ECDHE_RSA_WITH_AES_128_GCM_SHA256\n  ciphers
      ECDHE_ECDSA_WITH_AES_128_CBC_SHA256\n  ciphers
      ECDHE_RSA_WITH_AES_128_CBC_SHA256\n  ciphers
      ECDHE_ECDSA_WITH_AES_128_CBC_SHA\n  ciphers
      ECDHE_RSA_WITH_AES_128_CBC_SHA\n  ciphers
      DHE_DSS_WITH_AES_128_GCM_SHA256\n  ciphers
      DHE_RSA_WITH_AES_128_GCM_SHA256\n  ciphers
      DHE_RSA_WITH_AES_128_CBC_SHA256\n  ciphers
      DHE_DSS_WITH_AES_128_CBC_SHA256\n  ciphers DHE_RSA_WITH_AES_128_CBC_SHA\n 
      ciphers DHE_DSS_WITH_AES_128_CBC_SHA\n  ciphers
      RSA_WITH_AES_128_GCM_SHA256\n  ciphers RSA_WITH_AES_128_CBC_SHA256\n 
      ciphers RSA_WITH_AES_128_CBC_SHA\n  idcred webmgmt-credentials\n  no
      request-client-auth \n  require-client-auth \n  validate-client-cert \n 
      send-client-auth-ca-list \n  caching \n  cache-timeout 300\n  cache-size
      20\n  ssl-options \"\" \n  max-duration 60\n  max-renegotiation-allowed
      0\n  no prohibit-resume-on-reneg \n  no compression \n  no
      allow-legacy-renegotiation \n  prefer-server-ciphers \n  curves
      secp521r1\n  curves secp384r1\n  curves secp256k1\n  curves secp256r1\n 
      no prioritize-chacha \nexit\n%endif%\nexit\n\nweb-mgmt\n  admin-state
      \"enabled\"\n  local-address \"0.0.0.0\" \"9090\"\n  save-config-overwrite
      \n  idle-timeout 0\n  ssl-config-type server\n  ssl-server
      webmgmt-service\n  no disable-csrf \n  enable-sts
      \nexit\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"domain-config","namespace":"datapower"}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: '2022-04-06T15:23:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:default.cfg': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
data:
  default.cfg: >
    top; configure terminal; suppress-warnings; exec config:///auto-user.cfg; no
    suppress-warnings

    crypto
      certificate "webmgmt-cert" "sharedcert:///myCA.pem"
    exit

    crypto
      key "webmgmt-key" "sharedcert:///myCA.key"
    exit

    crypto
      idcred "webmgmt-credentials" "webmgmt-key" "webmgmt-cert"
    exit

    crypto
      
    %if% available "ssl-server"

    ssl-server "webmgmt-service"
      protocols "TLSv1d1+TLSv1d2+TLSv1d3" 
      ciphers AES_256_GCM_SHA384
      ciphers CHACHA20_POLY1305_SHA256
      ciphers AES_128_GCM_SHA256
      ciphers ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      ciphers ECDHE_RSA_WITH_AES_256_GCM_SHA384
      ciphers ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
      ciphers ECDHE_RSA_WITH_AES_256_CBC_SHA384
      ciphers ECDHE_ECDSA_WITH_AES_256_CBC_SHA
      ciphers ECDHE_RSA_WITH_AES_256_CBC_SHA
      ciphers DHE_DSS_WITH_AES_256_GCM_SHA384
      ciphers DHE_RSA_WITH_AES_256_GCM_SHA384
      ciphers DHE_RSA_WITH_AES_256_CBC_SHA256
      ciphers DHE_DSS_WITH_AES_256_CBC_SHA256
      ciphers DHE_RSA_WITH_AES_256_CBC_SHA
      ciphers DHE_DSS_WITH_AES_256_CBC_SHA
      ciphers RSA_WITH_AES_256_GCM_SHA384
      ciphers RSA_WITH_AES_256_CBC_SHA256
      ciphers RSA_WITH_AES_256_CBC_SHA
      ciphers ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      ciphers ECDHE_RSA_WITH_AES_128_GCM_SHA256
      ciphers ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
      ciphers ECDHE_RSA_WITH_AES_128_CBC_SHA256
      ciphers ECDHE_ECDSA_WITH_AES_128_CBC_SHA
      ciphers ECDHE_RSA_WITH_AES_128_CBC_SHA
      ciphers DHE_DSS_WITH_AES_128_GCM_SHA256
      ciphers DHE_RSA_WITH_AES_128_GCM_SHA256
      ciphers DHE_RSA_WITH_AES_128_CBC_SHA256
      ciphers DHE_DSS_WITH_AES_128_CBC_SHA256
      ciphers DHE_RSA_WITH_AES_128_CBC_SHA
      ciphers DHE_DSS_WITH_AES_128_CBC_SHA
      ciphers RSA_WITH_AES_128_GCM_SHA256
      ciphers RSA_WITH_AES_128_CBC_SHA256
      ciphers RSA_WITH_AES_128_CBC_SHA
      idcred webmgmt-credentials
      no request-client-auth 
      require-client-auth 
      validate-client-cert 
      send-client-auth-ca-list 
      caching 
      cache-timeout 300
      cache-size 20
      ssl-options "" 
      max-duration 60
      max-renegotiation-allowed 0
      no prohibit-resume-on-reneg 
      no compression 
      no allow-legacy-renegotiation 
      prefer-server-ciphers 
      curves secp521r1
      curves secp384r1
      curves secp256k1
      curves secp256r1
      no prioritize-chacha 
    exit

    %endif%

    exit


    web-mgmt
      admin-state "enabled"
      local-address "0.0.0.0" "9090"
      save-config-overwrite 
      idle-timeout 0
      ssl-config-type server
      ssl-server webmgmt-service
      no disable-csrf 
      enable-sts 
    exit
