apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: webgui-deployment
  labels:
    app.kubernetes.io/instance: datapower-webgui-deployment
    app.kubernetes.io/managed-by: datapower-operator
    app.kubernetes.io/name: webgui-deployment
    app.kubernetes.io/part-of: ibm-datapower-webgui-deployment
spec:
  license:
    accept: true
    license: L-RJON-CCCP46
    use: nonproduction
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: '1'
      memory: 4Gi
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /
      port: 7879
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  users:
    - accessLevel: privileged
      name: admin
      passwordSecret: datapower-user
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /
      port: 7879
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  domains:
    - certs:
        - certType: sharedcerts
          secret: datapower-cert
      dpApp:
        config:
          - domain-config
      name: default
  imagePullPolicy: IfNotPresent
  version: 10.0-cd
  podManagementPolicy: Parallel
  replicas: 1
  labels:
    app: webgui-deployment